version: '3'
services:
  db:
    container_name: lotterydb
    build:
      # dockerfileの名前だけ指定する
      dockerfile: Dockerfile
      # contextで場所を指定する
      context: ./postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
        - dbvolume:/var/lib/postgresql/data
  web:
    container_name: lottery_batch
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8888"]
    ports:
      - "8888:8888"
    environment:
      - AWS_ACCESS_KEY_LOTTERY=${AWS_ACCESS_KEY_LOTTERY}
      - AWS_SECRET_ACCESS_KEY_LOTTERY=${AWS_SECRET_ACCESS_KEY_LOTTERY}
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  dbvolume: